site_name: Portal de Integración – InvoiCy Argentina
site_url: https://migrate-company.github.io/PortalInvoiCyArgentina

#Aqui vão os links do MENU
nav:
nav:
  - Início: index.md
  - Integración:
    - API REST: Integración/Integracion_API_REST.md
  - Downloads: Integración/downloads.md
  - Release Notes: Revisiones\Release Notes.md
  - FAQ: FAQ.md

  #Fim definição de MENU

plugins:
  - search:
      lang: es
  - git-authors:
      enabled: true
      show_contribution: true
      show_email_address: true
      add_co_authors: true
      sort_authors_by: contribution
      #authorship_threshold_percent: 10
      enabled_on_serve: true
      exclude:
        - index.md
        - ES\Invoicy\news\index.md
  - glightbox:
      touchNavigation: true
      effect: zoom
      zoomable: true
  - git-revision-date-localized:
      enabled: true
      locale: es
      type: date
      exclude:
        - index.md
        - ES\Invoicy\news\index.md
        # - about.md
        
  #- i18n:
      # docs_structure: suffix
      # fallback_to_default: true
      # reconfigure_material: true
      # reconfigure_search: true
      # languages:

      #   - locale: es
      #     name: Español
      #     build: true
      #     copyright: "Todos los derechos reservados"
      #     site_name: "InvoiCy Uruguay"
      #     nav_translations:
      #       Planos: Planes
      #       Inicio: Comenzar

      #   - locale: pt
      #     name: Português
      #     build: true
      #     default: true
      #     copyright: "Todos os direitos reservados"
      #     site_name: "InvoiCy Uruguai"
          
      #   - locale: en
      #     name: English
      #     build: true
      #     copyright: "All rights reserved"
      #     site_name: "InoviCy Uruguay"
      #     nav_translations:
      #       Planos: Plans
      #       Inicio: Geting started
            
      #   - locale: "null"
      #     name: Help translating
      #     build: false
      #     fixed_link: https://github.com/migrate-company/bms-core-doc/issues

use_directory_urls: false

theme:
  logo: https://migrate-company.github.io/PortalInvoiCyUruguay/img/InvoicyforDev.png
  name: material
  # locale: es
  language: es
  custom_dir: overrides
  favicon: https://migrate-company.github.io/PortalInvoiCyUruguay/img/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: cambiar al modo oscuro
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: cambiar al modo claro
  icon:
    annotation: material/plus-circle
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select

extra_css:
  - stylesheets/extra.css
  - stylesheets/mkdocs-plugin/neoteroi.css

watch:
  - overrides

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      # css_class: 'highlight'
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.keys
  - neoteroi.timeline